from typing import Dict, Any

SCHEMA_CATALOG: Dict[str, Dict[str, Any]] = {
    # Summary & Analytics Schema (public)
    "consumers": {
        "description": "Information about energy consumers, customers, and facilities.",
        "columns": {
            "consumer_id": "Unique consumer identifier string (e.g., '67002820', '67001972').",
            "name": "Full legal or company name of the consumer.",
            "cluster_id": "Foreign key referencing clusters.cluster_id.",
            "location_id": "Foreign key referencing locations.location_id.",
            "category": "Consumer classification: 'Industrial', 'Commercial', or 'Residential'.",
            "join_date": "Date when consumer enrolled."
        }
    },
    "consumption": {
        "description": "Hourly electricity consumption readings for each consumer.",
        "columns": {
            "consumer_id": "Foreign key referencing consumers.consumer_id.",
            "timestamp": "Timestamp of hourly measurement.",
            "consumption": "Electricity energy consumed in kilowatt-hours (kWh) for that hour.",
            "status": "Quality status of reading ('VALID', 'ESTIMATED', etc.)."
        }
    },
    "predictions": {
        "description": "Hourly forecasted / predicted electricity consumption values generated by ML models.",
        "columns": {
            "consumer_id": "Foreign key referencing consumers.consumer_id.",
            "timestamp": "Timestamp of the forecast hour.",
            "predicted_consumption": "Model predicted electricity consumption in kWh.",
            "model_version": "Version of forecasting model (e.g. 'v1.0')."
        }
    },
    "clusters": {
        "description": "Geographic or operational consumer group clusters.",
        "columns": {
            "cluster_id": "Primary key identifier for cluster.",
            "name": "Cluster group name (e.g. 'Industrial Zone East').",
            "region": "Sub-region or zone name."
        }
    },
    "locations": {
        "description": "City and state locations.",
        "columns": {
            "location_id": "Primary key location identifier.",
            "city": "City name (e.g. 'Mumbai', 'Pune', 'Nagpur').",
            "state": "State name (e.g. 'Maharashtra').",
            "postal_code": "Postal code."
        }
    },
    "meters": {
        "description": "Electricity meter hardware assigned to consumers.",
        "columns": {
            "meter_id": "Unique meter serial/ID string.",
            "consumer_id": "Foreign key referencing consumers.consumer_id.",
            "install_date": "Date meter installed.",
            "meter_type": "Type of meter (e.g. 'Smart Three-Phase').",
            "status": "Operational status ('ACTIVE', 'INACTIVE')."
        }
    },
    "daily_summary": {
        "description": "Pre-calculated daily aggregated electricity metrics per consumer.",
        "columns": {
            "consumer_id": "Foreign key referencing consumers.consumer_id.",
            "date": "Date of summary.",
            "total_consumption": "Sum of consumption for the full day in kWh.",
            "avg_consumption": "Average hourly consumption for the day in kWh.",
            "max_consumption": "Peak hourly consumption of the day in kWh.",
            "min_consumption": "Minimum hourly consumption of the day in kWh."
        }
    },
    "consumer_predictions": {
        "description": "Analytical view comparing actual consumption vs predicted consumption per hour, including percentage exceeded.",
        "columns": {
            "consumer_id": "Consumer identifier.",
            "consumer_name": "Consumer company/person name.",
            "timestamp": "Reading timestamp.",
            "actual_consumption": "Actual consumption reading in kWh.",
            "predicted_consumption": "Predicted consumption reading in kWh.",
            "difference": "actual_consumption - predicted_consumption.",
            "percentage_exceeded": "Percentage by which actual exceeded predicted: ((actual - predicted) / predicted) * 100."
        }
    },
    "consumer_daily_summary": {
        "description": "Analytical view joining consumer details, cluster, location, and daily aggregated summary.",
        "columns": {
            "consumer_id": "Consumer identifier.",
            "consumer_name": "Name of consumer.",
            "category": "Consumer category.",
            "cluster_name": "Cluster name.",
            "city": "City.",
            "date": "Summary date.",
            "total_consumption": "Total daily kWh.",
            "avg_consumption": "Average hourly kWh.",
            "max_consumption": "Peak hourly kWh.",
            "min_consumption": "Minimum hourly kWh."
        }
    },
    "consumer_cluster_summary": {
        "description": "Analytical view providing aggregated metrics per cluster.",
        "columns": {
            "cluster_id": "Cluster ID.",
            "cluster_name": "Cluster name.",
            "region": "Region name.",
            "total_consumers": "Count of consumers in cluster.",
            "cluster_avg_consumption": "Average consumption across cluster.",
            "cluster_total_consumption": "Total consumption across cluster."
        }
    },

    # Production Data Lake Mappings (epdatalake schema)
    "epdatalake.consumer_mapping": {
        "description": "Maps Distribution Transformers (DTR) to connected consumer numbers.",
        "columns": {
            "DTR_STRUC_CODE": "Transformer structure code string.",
            "CONS_NO": "Consumer service number (matches lt_consumer_master.SCNO)."
        }
    },
    "epdatalake.dtr_master": {
        "description": "Master table for Distribution Transformers (DTR) containing technical details, capacity, phase, location, and geo-coordinates.",
        "columns": {
            "ID": "Unique DTR Master record identifier.",
            "DTR_STRUCTURE_CODE": "DTR structure code.",
            "DTR_LOCATION": "Physical location description of DTR.",
            "FEEDER_CODE": "Parent feeder code.",
            "PHASE": "Phase configuration of transformer.",
            "CAPACITY": "Transformer capacity rating (kVA).",
            "NO_OF_METERS": "Number of connected meters.",
            "METER_NUM_1": "Primary meter serial number.",
            "METER_NUM_2": "Secondary meter serial number.",
            "METER_NUM_3": "Tertiary meter serial number.",
            "GLAT": "Geographic latitude coordinate.",
            "GLONG": "Geographic longitude coordinate."
        }
    },
    "epdatalake.fdr_dtr_newcharge": {
        "description": "Mapping table between DTR ID and new AMR meter serial numbers (MSN).",
        "columns": {
            "DTR_ID": "DTR structure code (matches consumer_mapping.DTR_STRUC_CODE).",
            "DTR_MASTER_ID": "Foreign key referencing dtr_master.ID.",
            "NEW_MTR_MSN": "New AMR meter serial number (matches t_nw_blp.msn).",
            "NEW_MTR_MAKE": "Meter manufacturer make.",
            "NEW_MTR_MF": "Meter multiplication factor.",
            "NEW_MTR_CT_RATIO": "Current Transformer ratio.",
            "NEW_MTR_PT_RATIO": "Potential Transformer ratio.",
            "NEW_MTR_INSTALLATION_DATETIME": "Meter installation timestamp."
        }
    },
    "epdatalake.t_nw_blp": {
        "description": "Automated Meter Reading (AMR) block load profile (BLP) consumption data for DTR meters.",
        "columns": {
            "msn": "Meter serial number (matches fdr_dtr_newcharge.NEW_MTR_MSN).",
            "ts": "Reading timestamp.",
            "vah_imp": "Apparent imported energy reading (kVAh/kWh)."
        }
    },
    "epdatalake.lt_consumer_master": {
        "description": "Low Tension (LT) consumer master record containing contract load, category, phase, and unique service keys.",
        "columns": {
            "ID": "Consumer ID (matches lt_meter_data.CONS_NUMBER).",
            "SCNO": "Consumer Service Number (matches consumer_mapping.CONS_NO).",
            "UKSCNO": "Unique Key Service Number (matches smart_meters_install_m.UKSCNO).",
            "NAME": "Full name of LT consumer.",
            "CATEGORY": "Consumer category (e.g. Domestic, Commercial).",
            "PHASE": "Phase configuration ('1 Phase', '3 Phase').",
            "CONTRACTED_LOAD": "Contracted load rating.",
            "CONNECTED_LOAD": "Connected load rating.",
            "LOAD_TYPE": "Load type classification.",
            "FEEDER_NUM": "Feeder number.",
            "TRANS_STRUC_CODE": "Transformer structure code.",
            "BILLING_STATUS": "Billing status.",
            "SM_MTR": "Smart meter flag.",
            "NET_METERING": "Net metering status."
        }
    },
    "epdatalake.smart_meters_install_m": {
        "description": "Smart meter installation master linking UKSCNO service key to smart meter serial numbers (MTR_SNO).",
        "columns": {
            "UKSCNO": "Unique Key Service Number (matches lt_consumer_master.UKSCNO).",
            "MTR_SNO": "Smart meter serial number (matches t_blp_sp.msn or t_blp_tp.msn).",
            "MTR_TYPE": "Smart meter type.",
            "CONSUMER_MOBILENO": "Registered consumer mobile number.",
            "LATITUDE": "Latitude coordinate of smart meter.",
            "LONGITUDE": "Longitude coordinate of smart meter."
        }
    },
    "epdatalake.t_blp_sp": {
        "description": "1-Phase (Single Phase) smart meter block load profile consumption data.",
        "columns": {
            "msn": "Smart meter serial number (matches smart_meters_install_m.MTR_SNO).",
            "ts": "Consumption timestamp.",
            "vah_imp": "Imported energy consumption reading in kWh/kVAh."
        }
    },
    "epdatalake.t_blp_tp": {
        "description": "3-Phase (Three Phase) smart meter block load profile consumption data.",
        "columns": {
            "msn": "Smart meter serial number (matches smart_meters_install_m.MTR_SNO).",
            "ts": "Consumption timestamp.",
            "vah_imp": "Imported energy consumption reading in kWh/kVAh."
        }
    },
    "epdatalake.lt_meter_data": {
        "description": "Non-smart metered LT consumer manual/periodic reading data.",
        "columns": {
            "CONS_NUMBER": "Consumer ID (matches lt_consumer_master.ID).",
            "PRESENT_READING": "Present meter reading value.",
            "PREV_READING": "Previous meter reading value.",
            "PRESENT_MTRRDDATE": "Present reading date timestamp.",
            "PREV_MTRRDDATE": "Previous reading date timestamp."
        }
    },
    "epdatalake.ht_consumer_master": {
        "description": "High Tension (HT) consumer master table containing contracted demand, supply voltage, and meter details.",
        "columns": {
            "ID": "HT consumer ID.",
            "CONS_NUMBER": "HT consumer service number.",
            "NAME": "Name of HT consumer.",
            "TYPE_OF_SUPPLY": "Supply type classification.",
            "CATEGORY": "Consumer category.",
            "POWER_LOAD": "Power load limit.",
            "CONTRACT_DEMAND": "Contract demand limit (kVA).",
            "CONNECTED_LOAD": "Connected load limit.",
            "SUPPLY_VOLTAGE": "Supply voltage level.",
            "ACTUAL_VOLTAGE": "Actual voltage level.",
            "FEEDER_NUM": "Feeder number.",
            "FEEDER_CODE": "Feeder code.",
            "TRANS_STRUC_CODE": "Transformer structure code.",
            "TRANS_LOCATION": "Transformer location description.",
            "TRANS_SER_NUM": "Transformer serial number.",
            "MTR_NO": "Meter serial number.",
            "METER_MAKE": "Meter manufacturer make.",
            "METER_TYPE": "Meter type.",
            "METERING_TYPE": "Metering type classification.",
            "LATITUDE": "Geographic latitude.",
            "LONGITUDE": "Geographic longitude.",
            "SMT_MTR": "Smart meter flag."
        }
    },
    "epdatalake.lt_billing_data": {
        "description": "Low Tension (LT) consumer billing records.",
        "columns": {
            "CONS_NO": "Consumer service number.",
            "BILL_DATE": "Billing date timestamp.",
            "BILL_AMOUNT": "Billed amount."
        }
    },
    "epdatalake.htbpbillprocess_t": {
        "description": "High Tension (HT) consumer billing process table.",
        "columns": {
            "CONS_NUMBER": "HT consumer service number.",
            "BILL_DATE": "Billing date timestamp.",
            "TOTAL_AMOUNT": "Total bill amount."
        }
    },
    "epdatalake.oracle.smart_meters_billdata": {
        "description": "Smart meter consumer billing dataset.",
        "columns": {
            "MTR_SNO": "Smart meter serial number.",
            "BILL_DATE": "Billing date timestamp.",
            "BILL_AMOUNT": "Billed amount."
        }
    },
    "epdatalake.lt_category_master": {
        "description": "Master table defining LT consumer categories and tariff codes.",
        "columns": {
            "ID": "Category record ID.",
            "NAME": "Category name (e.g. Domestic, Commercial).",
            "CAT_CODE": "Category classification code.",
            "SCDESC": "Sub-category description."
        }
    }
}
